[colors.primary]
background = '#191323'
foreground = '#cccccc'

[colors.normal]
black   = '#17141f'
red     = '#ff6b7f'
green   = '#00bd9c'
yellow  = '#e6c62f'
blue    = '#22e8df'
magenta = '#dc396a'
cyan    = '#56b6c2'
white   = '#f1f1f1'

[colors.bright]
black   = '#495162'
red     = '#fe9ea1'
green   = '#98c379'
yellow  = '#f9e46b'
blue    = '#91fff4'
magenta = '#da70d6'
cyan    = '#bcf3ff'
white   = '#ffffff'
